export const getTimelineEvents = (t) => [
    { year: '1998', event: t("Година на изградба.") },
    { year: '2010', event: t("Година на верификација.") },
    { year: '2014', event: 'Recognized as the best regional high school in the country.' },
    { year: '2017', event: 'Launched online learning platforms and integrated technology into teaching.' },
]

export const getAdministrativeStaff = (t) => [
    {
        name: t('Бенази Шемовска'),
        position: t('Директор'),
        image: 'https://via.placeholder.com/150',
        bio: 'With 20 years of experience in education, Jane leads the school with a passion for excellence.',
      },
      {
        name: t('Зеќир Исовски'),
        position: t('Помошен Директор'),
        image: 'https://via.placeholder.com/150',
        bio: 'John oversees academic programs and ensures every student reaches their full potential.',
      },
      {
        name: t('Лумтарије Бастри'),
        position: t('Сметководител'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Семина Ракиповска'),
        position: t('Педагог'),
        image: 'https://via.placeholder.com/150',
        bio: 'John oversees academic programs and ensures every student reaches their full potential.',
      },
      {
        name: t('Халиме Сулејман'),
        position: t('Секретар'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Шпреза Илјазовска'),
        position: t('Социолог'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Наџир Шемовски'),
        position: t('Социолог'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Ајтен Мала'),
        position: t('Психолог'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Реулета Ракиповска'),
        position: t('Библиотекар'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
]

export const getSchoolBoard = (t) => [
    {
        name: t('Џошкун Зеќир'),
        position: t('Од редот на наставниците - Член'),
        image: 'https://via.placeholder.com/150',
        bio: 'With 20 years of experience in education, Jane leads the school with a passion for excellence.',
      },
      {
        name: t('Асан Мемедовски'),
        position: t('Од редот на наставниците - Член'),
        image: 'https://via.placeholder.com/150',
        bio: 'John oversees academic programs and ensures every student reaches their full potential.',
      },
      {
        name: t('Арта Папранику'),
        position: t('Од редот на наставниците - Член'),
        image: 'https://via.placeholder.com/150',
        bio: 'John oversees academic programs and ensures every student reaches their full potential.',
      },
      {
        name: t('Белур Џаферовски'),
        position: t('Од редот на родителите - Претседател'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Зенун Шаќир'),
        position: t('Од редот на родителите - Заменик Претседател'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Арсим Исламовски'),
        position: t('Од редот на родителите - Член'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Суад Скендер'),
        position: t('Од Локална Самоуправа - Центар Жупа'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Беглија Вејселовска'),
        position: t('Од редот на учениците'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Бастри Есра'),
        position: t('Од редот на учениците'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
]

export const getTechnicalStaff = (t) => [
    {
        name: t('Цено Вејселовски'),
        position: t('Технички персонал'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Азем Алили'),
        position: t('Технички персонал'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Алахудин Шемовски'),
        position: t('Технички персонал'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Муќизе Камберовска'),
        position: t('Технички персонал'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Зухра Амети'),
        position: t('Технички персонал'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Руждија Дурмишоска'),
        position: t('Технички персонал'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Мефмед Лимановски'),
        position: t('Технички персонал'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Велија Сеферовски'),
        position: t('Технички персонал'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
]


export const getEducationalStaff = (t) => [
    {
        name: t('Дилавер Сулемановски'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Нузи Ризвановски'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Асан Мемедовски'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Буран Селмановски'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Бјехула Веледин'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Ќаусер Јани'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Тирона Цами'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Џошкун Зеќир'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Aџи Зеќир'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Тајре Асан'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Зини Скендер'),
        position: t('Наставник и воспитувач'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Џансу Рахман'),
        position: t('Психолог'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Ќани Сеадиновски'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Зулбеар Ракиповски'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Ќаил Ракиповски'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Мефаил Исовски'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Мунтас Муслиовски'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Барда Ракиповска'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Ајрис Беќировски'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Нахида Беќировска'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Неџмија Мерсимовска'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Зихни Сејди'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Рамазан Асан'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Мерилда Шакир'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Ајбакан Асан'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Нагије Емро'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Дамаил Муратоски'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Илза Карамети'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Лејла Шаиновска'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Севинч Шеху'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Лиридона Мала'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Арта Папранику'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Кефсер Ф.Аџиевска'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Џошкун Ариф'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Мимоза Лиман'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Адмир Мустафоски'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Бенјамин Аџиоски'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Сонер Незировски'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Неџметин Асан'),
        position: t('Наставник'),
        image: 'https://via.placeholder.com/150',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
]