
export const getSchoolInfo = (t) => [
    { data: '1998', typeOfData: t("Година на изградба:") },
    { data: '2010', typeOfData: t("Година на верификација:") },
    { data: t('Совет на Општина Центар Жупа'), typeOfData: t("Основано од: ") },
    { data: t('2564 (м2)'), typeOfData: t("Внатрешна површина на улилиштето (м2): ")},
    { data: t('6131 (м2)'), typeOfData: t("Училишен двор (м2): ")},
    { data: t('Спортска сала: 640 (м2) + Игралиште 3050 (м2)'), typeOfData: t("Површина на спортски терени и игралишта: ")},
    { data: t('31'), typeOfData: t("Број на паралелки: ")},
    { data: t('5'), typeOfData: t("Број на комбинирани паралелки: ")},
    { data: t('Македонски - Турски - Албански'), typeOfData: t("Јазик / јазици на кој / кои се реализира наставата во училиштето: ")},
]

export const getAdministrativeStaff = (t) => [
    {
        name: t('Бенази Шемовска'),
        position: t('Директор'),
        image: '/staff-images/placeholder_man.png',
        bio: 'With 20 years of experience in education, Jane leads the school with a passion for excellence.',
      },
      {
        name: t('Зеќир Исовски'),
        position: t('Помошен Директор'),
        image: '/staff-images/placeholder_man.png',
        bio: 'John oversees academic programs and ensures every student reaches their full potential.',
      },
      {
        name: t('Лумтарије Бастри'),
        position: t('Сметководител'),
        image: '/staff-images/placeholder_woman.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Семина Ракиповска'),
        position: t('Педагог'),
        image: '/staff-images/placeholder_woman.png',
        bio: 'John oversees academic programs and ensures every student reaches their full potential.',
      },
      {
        name: t('Халиме Сулејман'),
        position: t('Секретар'),
        image: '/staff-images/placeholder_woman.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Шпреза Илјазовска'),
        position: t('Социолог'),
        image: '/staff-images/placeholder_woman.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Наџир Шемовски'),
        position: t('Социолог'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Ајтен Мала'),
        position: t('Психолог'),
        image: '/staff-images/placeholder_woman.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Реулета Ракиповска'),
        position: t('Библиотекар'),
        image: '/staff-images/placeholder_woman.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
]


export const getTechnicalStaff = (t) => [
    {
        name: t('Цено Вејселовски'),
        position: t('Технички персонал'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Азем Алили'),
        position: t('Технички персонал'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Алахудин Шемовски'),
        position: t('Технички персонал'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Муќизе Камберовска'),
        position: t('Технички персонал'),
        image: '/staff-images/placeholder_woman.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Зухра Амети'),
        position: t('Технички персонал'),
        image: '/staff-images/placeholder_woman.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Руждија Дурмишоска'),
        position: t('Технички персонал'),
        image: '/staff-images/placeholder_woman.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Мефмед Лимановски'),
        position: t('Технички персонал'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Велија Сеферовски'),
        position: t('Технички персонал'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
]


export const getEducationalStaff = (t) => [
    {
        name: t('Дилавер Сулемановски'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Нузи Ризвановски'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Асан Мемедовски'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Буран Селмановски'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Бјехула Веледин'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Ќаусер Јани'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_woman.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Тирона Цами'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_woman.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Џошкун Зеќир'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Aџи Зеќир'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Тајре Асан'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Зини Скендер'),
        position: t('Наставник и воспитувач'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Џансу Рахман'),
        position: t('Психолог'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Ќани Сеадиновски'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Зулбеар Ракиповски'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Ќаил Ракиповски'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Мефаил Исовски'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Мунтас Муслиовски'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Барда Ракиповска'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_woman.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Ајрис Беќировски'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Нахида Беќировска'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_woman.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Неџмија Мерсимовска'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_woman.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Зихни Сејди'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Рамазан Асан'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Мерилда Шакир'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_woman.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Ајбакан Асан'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Нагије Емро'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_woman.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Дамаил Муратоски'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Илза Карамети'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_woman.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Лејла Шаиновска'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_woman.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Севинч Шеху'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_woman.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Лиридона Мала'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_woman.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Арта Папранику'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_woman.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Кефсер Ф.Аџиевска'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_woman.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Џошкун Ариф'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Мимоза Лиман'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_woman.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Адмир Мустафоски'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Бенјамин Аџиоски'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Сонер Незировски'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
      {
        name: t('Неџметин Асан'),
        position: t('Наставник'),
        image: '/staff-images/placeholder_man.png',
        bio: 'Emily brings innovation and hands-on learning to the science curriculum.',
      },
]